# Generated by Django 2.2 on 2020-02-19 12:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('expected_time', models.IntegerField(default=0)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('end_time', models.TimeField(blank=True, default=datetime.time(0, 0), null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
