# Generated by Django 2.2 on 2020-02-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='expected_time',
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
